### ISSUE TITLE
Code improvements

### ISSUE THREAD

**Issue by dcmoura** [dcmoura/spyql#60]
Some cases where the code could be more pythonic:
- some `for` cycles where `range(len(l))` might be replaced by `enumerate`
- some functions where `yeld` might be used to return a generator

Changes should be accessed for performance.

**Comment by dcmoura** [comment]
Also check flake8 warnings

**Comment by Hayashi-Yudai** [comment]
May I do it?

**Comment by dcmoura** [comment]
Yes, go for it! This is is great for first time contributors. Check the CONTRIBUTING file to understand how to setup the dev environment and start by running the tests before making any change. Once you are good, you may start changing the code while making sure that tests continue passing. Let me know if you have any question. Thank you!

**Comment by Hayashi-Yudai** [comment]
@dcmoura 

I have a question.

> some functions where `yield` might be used to return a generator

What does this refer to? Are there functions which return large list?

**Comment by dcmoura** [comment]
When I start coding SPyQL There were some Python patterns that I was not familiar with. Mainly the use of a) yield and b) enumerate. The ideia is to try to understand where the use of such patterns can help making the code cleaner and/or increase performance. This does not need to be exhaustive. @Hayashi-Yudai

**Comment by dcmoura** [comment]
Closed by #82
