### ISSUE TITLE
404 status on downloading sample.csv file

### ISSUE THREAD

**Issue by maxlit** [dcmoura/spyql#81]
wget https://raw.githubusercontent.com/dcmoura/blogposts/spyql_cell_towers/spyql_cell_towers/sample.csv  gives 404 status

**Comment by dcmoura** [comment]
Thank you, forgot to update the linked after merging to master. Here's the updated URL:

https://raw.githubusercontent.com/dcmoura/blogposts/master/spyql_cell_towers/sample.csv

**Comment by dcmoura** [comment]
Blogpost updated.
Thank you so much for contributing @maxlit :-D
